spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://113.54.236.8:3306/paiban?serverTimezone=GMT%2B8&characterEncoding=utf8
    ##username: root
    #password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://113.54.236.8:5432/postgres
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      database: 0
      host: "1.2.30.40"
      port: 6379
      password: "123456"
      client-name:
        # 连接超时时间 （毫秒）
        timeout: 5000
        # 配置 redis 连接池
        jedis:
          pool:
            # 连接池最大连接数　（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 连接池的最大空闲连接
            max-idle: 8
            # 连接池中 最小空闲连接
            min-idle: 0
  thymeleaf:
    cache: false
static-locations: classpath:static/
server:
  port: 8080
  shutdown: graceful
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:8761
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.example.demo
  type-handlers-package: com.example.demo.methods.JsonbTypeHandler
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    configuration-interceptors: com.example.demo.config.MyBatisPlusConfig.